server:
  port: 8080

app:
  message: "Hello Client User, from the Secure Config Server (Service)!"
  environment: "Cloud Config"
  feature-toggle:
    enableBeta: true
  user:
    name: "John Doe"
    role: SSL Client