version: '3.8'

services:
  springboot-app:
    container_name: test-app-profile1
    hostname: test-app-profile1
    image: test-app:profile1
    ports:
      - "8081:8081"
    restart: always
    networks:
      - cloud-config-network # Create a network for inter-service communication


networks:
  cloud-config-network:
    external: true

