version: '3.8'

services:
  springboot-app:
    container_name: secure-cloud-config-server
    hostname: secure-cloud-config-server
    image: secure-cloud-config-server:0.0.1
    ports:
      - "8888:8888"
    networks:
      - cloud-config-network
    restart: always

networks:
  cloud-config-network:
    external: true