version: '3.8'

services:
  springboot-app:
    container_name: secure-test-app-plaintext
    hostname: secure-test-app-plaintext
    image: secure-test-app:plaintext
    ports:
      - "8080:8080"
    networks:
      - cloud-config-network
    restart: always

networks:
  cloud-config-network:
    external: true