version: '3.8'

services:
  springboot-app:
    container_name: test-app-profile3
    hostname: test-app-profile3
    image: test-app:profile3
    ports:
      - "8083:8083"
    restart: always
    networks:
      - cloud-config-network # Create a network for inter-service communication


networks:
  cloud-config-network:
    external: true

