spring:
  application:
    name: client

  config:
    import: configserver:  # unsure about this entry

# Spring Cloud Config Client configuration
  cloud:
    config:
      uri: https://secure-cloud-config-server:8443
      fail-fast: true
      retry:
        initial-interval: 5000
        max-attempts: 6
      profile: ssl
